### ISSUE TITLE
Edge: Prev/Next buttons display on top of Modal overlays

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/cozy-sun-bear#116] opened 2017-12-15 15:57 UTC
In Edge 16 (and presumably below), the previous and next buttons are displaying on top of the table of contents and preferences modals.

The buttons should not appear when a modal is triggered.

![bs_win10_edge_16 0](https://user-images.githubusercontent.com/1686111/34049807-b9ee26f8-e186-11e7-889f-5c5a1b42c7a1.jpg)

![bs_win10_edge_16 0 1](https://user-images.githubusercontent.com/1686111/34049809-bccad86c-e186-11e7-9953-6d654bb2ab3c.jpg)

**Comment by conorom** [comment] 2018-01-08 22:51
Long story short, I think the workaround is to directly set the intended `z-index` value of `25` on `.modal__overlay`.

Long story long:

There are several "stacking context" bugs open for Edge/IE:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/4060238/
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/13392888/

The first one caught my eye because of the changing opacity of the CSB modal. However I think that the second issue may be closer to the root cause. `.cozy-modal` has `z-index: 25;` but this doesn't seem to be inherited by it's child, `.modal__overlay` at all (in IE/Edge), which is the div that needs to be on top when the user pops out the modal.

Note that the prev/next buttons have a parent with a `z-index: 10;`. Also note that `.cozy-control.cozy-panel-feedback`, which has `z-index: 2;` appears over `.modal__overlay` too (as visible in the screenshot), so it's as though the latter has no `z-index` at all when it should have inherited the value of `25`.

So, it seems as though the feedback and chevron elements are inheriting their intended values. This can be confirmed by setting a `z-index` on `.modal__overlay` above 2, which gets it "above" the feedback icon but not the chevron prev/next icons. You have to go above 10 for that, as you would expect.

**Comment by conorom** [comment] 2018-01-08 23:13
Scratch that, `z-index: 25` stops you from closing the modal by clicking the gray area outside the menu. Going for `15`.

**Closed** 2018-01-09 20:48 UTC
Labels: browser compatibility, bug, in progress
